apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7ihy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fnni-tenant/rhtap-demo-app/hacbs-test-project-7ihy@sha256:0772dbec7642949b28577293faf6f8d296cdf4b1c6be986b0a61212183356f54
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
