apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7ihy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7ihy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7ihy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7ihy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7ihy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fnni-tenant/rhtap-demo-app/hacbs-test-project-7ihy@sha256:0772dbec7642949b28577293faf6f8d296cdf4b1c6be986b0a61212183356f54
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
